✨ feat(front) PLAS-19 input ds component
Bastien-and-Gauvain/monorepo pull request #16
Opened 2023-09-19 22:07 UTC by Bassvelitchkine

# Context

This PR was formerly intended to encompass a single text entry molecule (i.e a text input and its corresponding label). I took upon myself to **extend the original requirement** and also add a *dropdown select entry* (i.e select input + label) to the task.

# Solution

Hence, the is what has been developed:
- A label component (*atom*)
- A text input component (*atom*)
- A select input component (*atom*)
- A text form entry (*molecule*)
- A dropdown select from entry (*molecule*)

Unsurprisingly, you'll see how it all articulates when running `pnpm storybook`

2023-09-19 22:10 UTC, Bassvelitchkine commented
Side notes:
1. Yes, **the commit history is a bit messy** as I had created the branch before the latest code was on github, then pulled remote changes to my local master branch, and then merged the master branch into the branch I had first created.
2. Yes, **there's more in this PR than in previous ones**. *Should I have split the text form entry and the select form entry in two distinct PRs?* Please let me know.

2023-09-19 22:13 UTC, Bassvelitchkine commented
And yes, **I'll have to extend the dropdown select component**. I've only built a basic one, but the smaller dark blue one (for notion db selection) is still missing. That's for another PR.

2023-09-20 20:30 UTC, Bassvelitchkine commented
I created the alternative dropdown after all :)

2023-09-20 21:04 UTC, GauvainThery commented
> Side notes:
> 
> 1. Yes, **the commit history is a bit messy** as I had created the branch before the latest code was on github, then pulled remote changes to my local master branch, and then merged the master branch into the branch I had first created.
> 2. Yes, **there's more in this PR than in previous ones**. _Should I have split the text form entry and the select form entry in two distinct PRs?_ Please let me know.

No worries, honestly we don't care about commits! And as long as you're under 500 lines to review, it's fine for me!

2023-09-20 21:06 UTC, GauvainThery requested changes
A few comments 🙈

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/labels/labels.tsx
> +  className?: string;
Add JSdoc comments to give information to the person using the component, same as we did with title for example.

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/inputs.stories.tsx
> +  component: TextInput,
```suggestion
```

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/inputs.stories.tsx
> +} satisfies Meta<TextInputProps | SelectInputProps>;
No need to pass the generic type, it'll become a mess when we'll have many inputs

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/inputs.stories.tsx
> +  component: TextInput,
No need as your story is not specific to one component

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/textInputs.tsx
> +};
Same here, add the JSdoc so that it's easy to know waht are the different args.

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/textInputs.tsx
> +  const inputRef = useRef<HTMLInputElement>(null);
Why useRef here?
You don't use it?

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +};
Idem (JSDoc)

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +};
Idem, JSDoc

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +  const inputRef = useRef<HTMLSelectElement>(null);
Same here for the use ref, not needed

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +};
Also, I think your missing label here

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +          {value}
you shouldn't use value here but a distinctive label

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +  initialValueIndex = 0,
I think it can be just initialValue here, index might be confusing. And then when you use, you just do a value === initialValue

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/molecules/formEntries/formEntries.stories.tsx
> +  component: TextEntry,
Not needed. I know there's a way to to make form entries a folder so that every element has its own story but still having one story file, but I coudn't find how to do it.

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +        className
```suggestion
'antialiased text-gray border border-solid border-gray rounded-md w-full p-2 focus:outline-none focus:border-cyan focus:ring-cyan'
```

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/textInputs.tsx
> +        'focus:border-cyan',
Same here, on one line

2023-09-20 21:06 UTC, GauvainThery commented on libs/design-system/src/atoms/inputs/textInputs.tsx
> +        'focus:border-cyan',
Or you can regroup if it makes sense, but no more than 2/3 groups

2023-09-20 21:53 UTC, Bassvelitchkine commented on libs/design-system/src/atoms/inputs/inputs.stories.tsx
> +  component: TextInput,
Ok, didn't know that. I was just reproducing the same "template". Thx

2023-09-20 21:54 UTC, Bassvelitchkine commented on libs/design-system/src/molecules/formEntries/formEntries.stories.tsx
> +  component: TextEntry,
Ok, apart from removing `component: TextEntry` I'm not sure what you want me to do here

2023-09-20 22:10 UTC, Bassvelitchkine commented on libs/design-system/src/atoms/inputs/textInputs.tsx
> +  const inputRef = useRef<HTMLInputElement>(null);
Yeah, I don't know. I thought they prevented the component from re-rendering. Tbh I kinda forgot what I used them for, what they're generally used for. The use case will come up I reckon, I'll refresh my memory then aha.

I'll remove it!

2023-09-20 22:20 UTC, Bassvelitchkine commented on libs/design-system/src/atoms/inputs/selectInputs.tsx
> +        className
"What was I thinking?" one might wonder 🙃

2023-09-20 22:23 UTC, Bassvelitchkine commented
So now, there's only one remaining comment I'm not quite sure how to deal with, but apart from that, we're good I guess

2023-09-21 20:03 UTC, GauvainThery commented on libs/design-system/src/molecules/formEntries/formEntries.stories.tsx
> +  component: TextEntry,
Just remove it's fine 👌 

What I'm trying to say is:
I like the idea of having only one file for all the inputs' stories. But we should be able to create a folder called inputs and have an independent story for each component. I tried to do this but couldn't figure it out, and IMHO we absolutely don't care 😅

2023-09-21 20:05 UTC, GauvainThery approved these changes
All good !

2023-09-21 20:24 UTC, Bassvelitchkine commented on libs/design-system/src/molecules/formEntries/formEntries.stories.tsx
> +  component: TextEntry,
Fair enough, thx for the clarification aha

2023-09-21 20:24 UTC, merged